[theme]
base                     = "dark"
backgroundColor          = "#242424"
secondaryBackgroundColor = "#2E2E2E"
primaryColor             = "#5B8DB8"
textColor                = "#DBDBDB"
font                     = "sans serif"

[server]
headless        = true
enableCORS      = false

[browser]
gatherUsageStats = false
