[theme]
base                     = "dark"
backgroundColor          = "#171717"
secondaryBackgroundColor = "#1C1C1C"
primaryColor             = "#4AD493"
textColor                = "#DBDBDB"
font                     = "sans serif"

[server]
headless        = true
enableCORS      = false

[browser]
gatherUsageStats = false
